MyPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from user.views import home, course, register_first

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', home, name='home'),
    path('course', course, name='course'),
    path('register/first', register_first, name='register_first'),
    path('user/', include('user.urls'), name='user'),
    path('shell/', include('shell.urls'), name='shell'),
    path('monitor/', include('monitor.urls'), name='monitor'),
    path('performance/', include('performance.urls'), name='perf'),
]

urlpatterns = [
    path(f'{settings.PREFIX}/', include(urlpatterns))
]

performance/urls.py
from django.urls import path
from django.conf import settings
from . import views
from . import planViews
from . import taskViews
from . import threadViews
from . import controllerViews
from . import sampleViews
from . import headerViews
from . import jmeterViews

app_name = 'perf'
urlpatterns = [
    path('home', taskViews.home, name='home'),
    path('delete', views.delete, name='delete'),
    path('setStatus', views.is_valid, name='set_status'),

    path('plan', planViews.home, name='plan_home'),
    path('plan/add', planViews.add, name='plan_add'),
    path('plan/edit', planViews.edit, name='plan_edit'),
    path('plan/copy', planViews.copy_plan, name='plan_copy'),
    path('plan/file/upload', planViews.upload_file, name='plan_upload_file'),
    path('plan/variable', planViews.edit_variable, name='plan_variable'),

    path('task', taskViews.home, name='task_home'),
    # path('task/register', taskViews.register, name='agent_register'),
    path('task/status', taskViews.get_running_status, name='task_status'),
    path('task/add', taskViews.add_to_task, name='task_add'),
    path('task/delete', taskViews.delete_task, name='task_delete'),
    path('task/start', taskViews.start_task, name='task_start'),
    path('task/stop', taskViews.stop_task, name='task_stop'),
    path('task/download', taskViews.download_file, name='task_download'),
    path('task/download/log', taskViews.download_log, name='task_download_log'),
    path('task/change', taskViews.change_tps, name='change_tps'),
    # path('task/register/getMessage', taskViews.set_message, name='task_set_message'),
    path('task/query', taskViews.query_data, name='task_query'),
    path('task/detail', taskViews.view_task_detail, name='task_detail'),
    path('task/getIdleServer', taskViews.get_idle_server, name='get_idle_server'),
    path('task/getUsedServer', taskViews.get_used_server, name='get_used_server'),
    path('task/getRunningServer', taskViews.get_running_server, name='get_running_server'),
    path('task/autoRun', views.request_auto_run, name='auto_run_test'),
    # path('task/cancel', views)

    path('group', threadViews.home, name='group_home'),
    path('group/add', threadViews.add_group, name='group_add'),
    path('group/edit', threadViews.edit_group, name='group_edit'),
    path('group/copy', threadViews.copy_group, name='group_copy'),
    path('group/cookie', threadViews.edit_cookie, name='group_cookie'),
    path('group/file/upload', threadViews.upload_file, name='group_upload_file'),
    path('group/file/delete', threadViews.delete_file, name='group_delete_file'),

    path('controller', controllerViews.home, name='controller_home'),
    path('controller/add', controllerViews.add_group, name='controller_add'),
    path('controller/copy', controllerViews.copy_controller, name='controller_copy'),
    path('controller/edit', controllerViews.edit_group, name='controller_edit'),

    path('sample', sampleViews.home, name='sample_home'),
    path('sample/header', sampleViews.get_from_header, name='sample_header_home'),
    path('sample/add', sampleViews.add_sample, name='sample_add'),
    path('sample/edit', sampleViews.edit_sample, name='sample_edit'),
    path('sample/copy', sampleViews.copy_sample, name='sample_copy'),
    path('header/getByMehtod', sampleViews.get_header_by_method, name='get_header_by_method'),

    path('header', headerViews.home, name='header_home'),
    path('header/add', headerViews.add_header, name='header_add'),
    path('header/edit', headerViews.edit_header, name='header_edit'),
    path('header/copy', headerViews.copy_header, name='header_copy'),

    path('jmeter', jmeterViews.home, name='jmeter_home'),
    path('jmeter/edit', jmeterViews.edit, name='jmeter_edit'),
    path('jmeter/upload', jmeterViews.upload_file, name='jmeter_upload'),
    path('jmeter/start', jmeterViews.add_to_task, name='jmeter_add'),

] if settings.IS_PERF == 1 else []

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('changePwd', views.change_pwd, name='change_pwd')
]

performance/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: leeyoshinari

import os
import time
import logging
import traceback
from django.db.models.deletion import ProtectedError
from django.conf import settings
from .models import TestPlan, ThreadGroup, TransactionController
from .models import HTTPRequestHeader, HTTPSampleProxy, PerformanceTestTask
from .taskViews import start_test, stop_test, change_tps_test
from .common.fileController import delete_local_file
from common.Result import result
# Create your views here.


logger = logging.getLogger('django')


def delete_file_from_disk(file_path):
    path_list = file_path.split('/')
    if settings.FILE_STORE_TYPE == '0':
        try:
            file_folder = os.path.join(settings.FILE_ROOT_PATH, path_list[-2])
            file_local_path = os.path.join(file_folder, path_list[-1])
            os.remove(file_local_path)
            _ = delete_local_file(file_folder)
        except FileNotFoundError:
            logger.warning(f"FileNotFound: No such file: {file_path}")
    else:
        settings.MINIO_CLIENT.delete_file(path_list[-2], path_list[-1])


def delete(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            delete_type = request.POST.get('type')
            delete_id = request.POST.get('id')
            if delete_type == 'plan':
                plan = TestPlan.objects.get(id=delete_id)
                if plan.is_file == 1:
                    delete_file_from_disk(plan.file_path)
                plan.delete()
            if delete_type == 'group':
                group = ThreadGroup.objects.get(id=delete_id)
                if group.file:
                    file_path = group.file.get('file_path')
                    delete_file_from_disk(file_path)
                group.delete()
            if delete_type == 'controller':
                TransactionController.objects.get(id=delete_id).delete()
            if delete_type == 'sample':
                HTTPSampleProxy.objects.get(id=delete_id).delete()
            if delete_type == 'header':
                HTTPRequestHeader.objects.get(id=delete_id).delete()
            if delete_type == 'task':
                task = PerformanceTestTask.objects.get(id=delete_id)
                if task.path:
                    delete_file_from_disk(task.path)
                task.delete()
            logger.info(f'{delete_type} {delete_id} is deleted success, operator: {username}, IP: {ip}')
            return result(msg='Delete success ~')
        except ProtectedError:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Delete failure, because it is referenced through protected foreign keys ~')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Delete failure ~')


def is_valid(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            set_type = request.POST.get('set_type')
            set_id = request.POST.get('id')
            is_valid = request.POST.get('is_valid')
            if set_type == 'plan':
                res = TestPlan.objects.get(id=set_id)
            if set_type == 'group':
                res = ThreadGroup.objects.get(id=set_id)
            if set_type == 'controller':
                res = TransactionController.objects.get(id=set_id)
            if set_type == 'sample':
                res = HTTPSampleProxy.objects.get(id=set_id)
            res.is_valid = is_valid
            res.operator = username
            res.save()
            logger.info(f'{set_type} {set_id} status is set to {is_valid} success, operator: {username}, IP: {ip}')
            return result(msg='Set success ~')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Set failure ~')


def request_auto_run(request):
    if request.method == 'GET':
        username = request.user.username
        ip = request.headers.get('x-real-ip')
        tasks = PerformanceTestTask.objects.filter(plan__schedule=1, status=0)
        logger.info(f'Total auto test task is {len(tasks)}')
        for task in tasks:
            index = 0
            total_index = len(task.plan.time_setting) - 1
            for timing in task.plan.time_setting:
                if index == 0:
                    settings.SCHEDULER.add_job(start_test, 'date', run_date=timing['timing'], args=[task.id, None, username, ip], id=f"{task.id}_{index}")
                elif index == total_index:
                    settings.SCHEDULER.add_job(stop_test, 'date', run_date=timing['timing'], args=[task.id, 'all', username, ip], id=f"{task.id}_{index}")
                else:
                    settings.SCHEDULER.add_job(change_tps_test, 'date', run_date=timing['timing'], args=[task.id, 'all', timing['value'], username, ip], id=f"{task.id}_{index}")
        logger.info(f'Auto run performance test task success, operator: {username}, IP: {ip}')
        return result(msg='success')


# def cancel_auto_task(request):


performance/templates/perf_home.html
{% extends 'template.html' %}
{% load static compress %}
{% block addcss %}
    {% compress css %}
    <link rel="stylesheet" href="{% static 'performance/css/home.css' %}">
    {% endcompress %}
{% endblock %}
{% block addjs %}
    {% compress js %}
    <script src="{% static 'performance/js/home.js' %}"></script>
    {% endcompress %}
    {% block add_js %}
    {% endblock %}
{% endblock %}
{% block addbody %}
    {% csrf_token %}
    <div class="container1">
        <div class="home_list"><a href="{% url 'home' %}">Home</a><span>>></span><a href="{% url 'perf:plan_home' %}">Performance Test</a>
        </div><a href="{% url 'user:logout' %}">Logout</a>
    </div>
    <div class="container2">
        <div class="list-icon" style="margin-top: 35px;"><a href="{% url 'perf:home' %}">Home</a></div>
        <div class="list-icon" title="Corresponds to Test Plan in JMeter."><a href="{% url 'perf:plan_home' %}">Test Plan</a></div>
        <div class="list-icon" title="Corresponds to Thread Group in JMeter."><a href="{% url 'perf:group_home' %}">Thread Group</a></div>
        <div class="list-icon" title="Corresponds to Transaction Controller in JMeter."><a href="{% url 'perf:controller_home' %}">Controller</a></div>
        <div class="list-icon" title="Corresponds to HTTP Request in JMeter."><a href="{% url 'perf:sample_home' %}">HTTP Sample</a></div>
        <div class="list-icon" title="Corresponds to HTTP Header Manager in JMeter."><a href="{% url 'perf:header_home' %}">HTTP Header</a></div>
        <div class="list-icon"><a href="{% url 'perf:jmeter_home' %}">Upload JMeter</a></div>
        <div class="list-icon"><a href="{% url 'perf:task_home' %}">Test Task</a></div>
    </div>
    <div class="container3">
        <div class="toolbar">
            {% block toolbar %}
                <div style="height: 35px;"><div class="navigate">
                        {% block navigate %}{% endblock %}
                    </div>
                    {% block searchBlock %}{% endblock %}
                </div>
            {% endblock %}
            <div class="vertical-bar"></div>
        </div>
        <div class="detail">
            {% block detail %}
                <div class="detail-action">
                    {% block detail_action %}
                    {% endblock %}
                </div>
                {% block other_content %}
                {% endblock %}
                <table id="layout-table" class="table table-bordered">
                    <thead>
                        {% block table_head %}
                        {% endblock %}
                    </thead>
                    <tbody id="tbody">
                        {% block table_body %}
                        {% endblock %}
                    </tbody>
                </table>
            {% endblock %}
            {% block back_body %}
            {% endblock %}
        </div></div>
    <div id="myModal"></div>
    <div class="modal_cover"><div class="modal_gif"></div></div>
{% block fenye %}
    <div class="fenye"><ul id="paging" class="pagination"></ul></div>
{% endblock %}
{% endblock %}
{% block backjs %}
    {% compress js %}
    <script src="{% static 'js/fenye.js' %}"></script>
    {% endcompress %}
{% endblock %}
{% block define_js %}
{% endblock %}