MyPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from user.views import home, course, register_first

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', home, name='home'),
    path('course', course, name='course'),
    path('register/first', register_first, name='register_first'),
    path('user/', include('user.urls'), name='user'),
    path('shell/', include('shell.urls'), name='shell'),
    path('monitor/', include('monitor.urls'), name='monitor'),
    path('performance/', include('performance.urls'), name='perf'),
]

urlpatterns = [
    path(f'{settings.PREFIX}/', include(urlpatterns))
]

shell/urls.py
from django.urls import path
from . import views

app_name = 'shell'
urlpatterns = [
    path('', views.index, name='index'),
    path('open', views.openssh, name='open_shell'),
    path('add/server', views.add_server, name='add_server'),
    path('get/server', views.get_server, name='get_server'),
    path('edit/server', views.edit_server, name='edit_server'),
    path('add/user', views.add_user, name='add_user'),
    path('create/group', views.create_group, name='create_group'),
    path('get/group', views.get_all_group, name='get_group'),
    path('create/room', views.create_room, name='create_room'),
    path('get/room', views.get_all_room, name='get_room'),
    path('delete/server', views.delete_server, name='delete_server'),
    path('search/server', views.search_server, name='search_server'),
    path('file/upload', views.upload_file, name='upload_file'),
    path('file/download', views.download_file, name='download_file'),

    path('package/home', views.package_home, name='package_home'),
    path('package/delete', views.delete_package, name='delete_package'),
    path('package/deploy', views.deploy_package, name='deploy_package'),
    path('package/stop', views.uninstall_deploy, name='stop_package'),
    path('package/upload', views.package_upload, name='upload_package'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('changePwd', views.change_pwd, name='change_pwd')
]

shell/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: leeyoshinari

from django.db import models
from django.contrib.auth.models import Group

# Create your models here.


class ServerRoom(models.Model):
    id = models.CharField(max_length=16, primary_key=True, verbose_name='primary key')
    name = models.CharField(max_length=32, verbose_name='server room name')
    type = models.IntegerField(default=0, verbose_name='server room type. 0-use to application, 1-use to middleware, 2-use to pressure test')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='Create time')
    update_time = models.DateTimeField(auto_now=True, verbose_name='Update time')
    operator = models.CharField(max_length=50, verbose_name='operator')
    objects = models.Manager()

    class Meta:
        db_table = 'server_room'


class GroupIdentifier(models.Model):
    id = models.CharField(max_length=16, primary_key=True, verbose_name='primary key')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='group id')
    key = models.CharField(max_length=32, verbose_name='group unique identifier')
    prefix = models.CharField(max_length=32, verbose_name='url path prefix')
    objects = models.Manager()

    class Meta:
        db_table = 'group_identifier'


class Servers(models.Model):
    id = models.CharField(max_length=16, primary_key=True, verbose_name='primary key')
    group = models.ForeignKey(Group, on_delete=models.PROTECT, verbose_name='group id')
    room = models.ForeignKey(ServerRoom, on_delete=models.PROTECT, verbose_name='server rooom')
    name = models.CharField(max_length=64, verbose_name='server name')
    host = models.CharField(max_length=20, verbose_name='server IP')
    port = models.IntegerField(default=22, verbose_name='ssh port')
    user = models.CharField(max_length=25, verbose_name='ssh login username')
    pwd = models.CharField(max_length=64, verbose_name='ssh login password')
    system = models.CharField(max_length=64, verbose_name='system')
    cpu = models.IntegerField(default=0, verbose_name='cpu cores (logical core)')
    arch = models.CharField(max_length=10, verbose_name='system architecture')
    mem = models.FloatField(default=0.0, verbose_name='memory(G)')
    disk = models.CharField(max_length=8, verbose_name='disk')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='Create time')
    update_time = models.DateTimeField(auto_now=True, verbose_name='Update time')
    creator = models.CharField(max_length=50, verbose_name='creator')
    operator = models.CharField(max_length=50, verbose_name='operator')
    objects = models.Manager()

    class Meta:
        db_table = 'server'
        indexes = [models.Index(fields=['host'])]


class Packages(models.Model):
    id = models.CharField(max_length=16, primary_key=True, verbose_name='primary key')
    name = models.CharField(max_length=64, verbose_name='package name')
    type = models.CharField(max_length=16, verbose_name='package type, monitor-agent, jmeter-agent, java, jmeter')
    system = models.CharField(max_length=64, verbose_name='system')
    arch = models.CharField(max_length=10, verbose_name='system architecture')
    path = models.CharField(max_length=128, verbose_name='package store path')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='Create time')
    update_time = models.DateTimeField(auto_now=True, verbose_name='Update time')
    operator = models.CharField(max_length=50, verbose_name='operator')
    objects = models.Manager()

    class Meta:
        db_table = 'packages'

shell/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: leeyoshinari

import os
import json
import logging
import traceback
from django.shortcuts import render, redirect
from django.http import StreamingHttpResponse
from django.conf import settings
from django.core import serializers
from django.forms.models import model_to_dict
from django.contrib.auth.models import User, Group
from django.db.models import Q
from django.db.models.deletion import ProtectedError
from common.Result import result
from common.generator import primaryKey
from common.customException import MyException
from .models import Servers, ServerRoom, GroupIdentifier, Packages
from .channel.ssh import get_server_info, UploadAndDownloadFile
from .channel.deployAgent import deploy, stop_deploy, check_deploy_status


logger = logging.getLogger('django')
current_path = os.path.abspath(os.path.dirname(__file__))
upload_file_path = os.path.join(current_path, 'uploadFile')
deploy_path = settings.DEPLOY_PATH
local_file_path = os.path.join(settings.BASE_DIR, 'static', 'autoDeploy')
if not os.path.exists(upload_file_path):
    os.mkdir(upload_file_path)
if not os.path.exists(local_file_path):
    os.mkdir(local_file_path)


def index(request):
    if request.method == 'GET':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            is_staff = request.user.is_staff
            page = request.GET.get('page')
            page_size = request.GET.get('pageSize')
            page = int(page) if page else 1
            page_size = int(page_size) if page_size else settings.PAGE_SIZE
            groups = request.user.groups.all()
            rooms = ServerRoom.objects.all().order_by('-create_time')
            total_num = Servers.objects.filter(group__in=groups).count()
            servers = Servers.objects.filter(group__in=groups).order_by('-id')[(page - 1) * page_size: page * page_size]
            logger.info(f'access shell index.html. operator: {username}, IP: {ip}')
            return render(request, 'index.html', context={'servers': servers, 'groups': groups, 'page': page,
                                                                'page_size': page_size, 'total_page': (total_num - 1) // page_size + 1,
                                                                'rooms': rooms, 'is_staff': is_staff, 'operator': username})
        except:
            logger.error(traceback.format_exc())
            return render(request, '404.html')
    else:
        return render(request, '404.html')


def add_server(request):
    if request.method == 'POST':
        try:
            ip = request.headers.get('x-real-ip')
            group_id = request.POST.get('GroupName')
            server_name = request.POST.get('ServerName')
            room_id = request.POST.get('ServerRoom')
            server_ip = request.POST.get('ServerIP')
            try:
                Servers.objects.get(host=server_ip)
                logger.info(f'server has been added ~ ')
                return result(code=2, msg='server has been added ~ ')
            except Servers.DoesNotExist:
                pass
            port = request.POST.get('Port')
            sshname = request.POST.get('UserName')
            password = request.POST.get('Password')
            current_time = request.POST.get('time')
            username = request.user.username
            system = ''
            cpu = 0
            arch = ''
            mem = 0
            disk = 0

            if password:
                datas = get_server_info(host=server_ip, port = int(port), user = sshname, pwd = password, current_time=current_time)
                if datas['code'] == 0:
                    system = datas['system']
                    cpu = datas['cpu']
                    mem = datas['mem']
                    disk = datas['disk']
                    arch = datas['arch']
                else:
                    return result(code=1, msg=datas['msg'])

            server = Servers.objects.create(id = current_time, group_id = group_id, name=server_name, room_id=room_id,
                                   host=server_ip, port = int(port), user = sshname, pwd = password, system = system,
                                   cpu = cpu, arch=arch, mem = mem, disk = disk, creator=username, operator=username)
            logger.info(f'Add server success. host: {server.host}, operator: {username}, time: {server.id}, IP:{ip}')
            return result(code=0, msg='Add server success ~ ')
        except Exception as err:
            logger.error(traceback.format_exc())
            return result(code=1, msg=err)

def get_server(request):
    if request.method == 'GET':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            server_id = request.GET.get('id')
            servers = Servers.objects.get(id=server_id)
            server_dict = model_to_dict(servers)
            server_dict.pop('pwd')
            logger.info(f'Get server {servers.host} info success, operator: {username}, IP: {ip}')
            return result(data=server_dict)
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Get server failure ~')

def edit_server(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            server_id = request.POST.get('ServerId')
            server_ip = request.POST.get('ServerIP')
            servers = Servers.objects.get(id=server_id, host=server_ip)
            servers.group_id = request.POST.get('GroupName')
            servers.name = request.POST.get('ServerName')
            servers.room_id = request.POST.get('ServerRoom')
            servers.port = request.POST.get('Port')
            servers.user = request.POST.get('UserName')
            servers.operator = username
            password = request.POST.get('Password')
            if password:
                servers.pwd = password
            servers.save()
            logger.info(f'Edit server success. host: {servers.host}, operator: {username}, id: {servers.id}, IP: {ip}')
            return result(msg='Edit server success ~ ')
        except Servers.DoesNotExist:
            logger.error(f'Please do not modify server id and host, operator: {username}, IP: {ip}')
            return result(code=1, msg='Please do not modify server id and host ~')
        except Exception as err:
            logger.error(traceback.format_exc())
            return result(code=1, msg=err)

def add_user(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            user_name = request.POST.get('UserName')
            group_name = request.POST.get('GroupName')
            operator = request.POST.get('Operator')
            groups = request.user.groups.get(id=group_name)
            users = User.objects.get(username=user_name)
            if operator == 'add':
                users.groups.add(groups.id)
                logger.info(f'add {user_name} to {groups.name} group success, operator: {username}, IP: {ip}')
                return result(msg='Add User success ~')
            else:
                users.groups.remove(groups.id)
                logger.info(f'Remove {user_name} from {groups.name} group success, operator: {username}, IP: {ip}')
                return result(msg='Remove User success ~')
        except User.DoesNotExist:
            logger.error(traceback.format_exc())
            return result(code=1, msg='User is not exist ~')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='System error ~')


def create_group(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            group_name = request.POST.get('GroupName')
            group_id = request.POST.get('GroupId')
            group_key = request.POST.get('GroupKey')
            group_type = request.POST.get('GroupType')
            prefix = request.POST.get('Prefix')
            if group_type == 'add':
                group = Group.objects.create(name=group_name)
                users = User.objects.filter(is_staff=1)
                for user in users:
                    user.groups.add(group.id)
                try:
                    identifier = GroupIdentifier.objects.get(key=group_key)
                    Group.objects.get(id=group.id).delete()
                    logger.error(f"{identifier.key} has existed, operator: {username}, IP: {ip}")
                    return result(code=1, msg=f"{identifier.key} has existed, Group Name is {identifier.group.name}")
                except GroupIdentifier.DoesNotExist:
                    identifier = GroupIdentifier.objects.create(id=primaryKey(), group_id=group.id, key=group_key, prefix=prefix)
            if group_type == 'delete':
                group = Group.objects.get(id=group_id).delete()
            logger.info(f'{group_type} group {group_name} success, operator: {username}, IP: {ip}')
            return result(msg='Create group success ~')
        except ProtectedError:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Cannot delete Group because it is referenced')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='System error ~')


def create_room(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')

shell/templates/index.html
{% extends 'shell_home.html' %}
{% load static compress %}
{% load myFilter %}
{% block container2 %}
    <div id="filter">
        <div style="width: 30%">
            {% if is_staff %}
                <button id="createGroup">Create Group</button>
                <button id="createRoom" style="width: 155px;">Create Server Room</button>
                <button id="addUser">Add User</button>
            {% endif %}
            <button id="addServer">Add Server</button>
        </div>
        <div style="width: 60%;">
            <label>ServerRoom: </label><input id="ServerRoom" type="text" placeholder="Server Room Name ~">
            <label>Group: </label><input id="groupName" type="text" placeholder="Group Name ~">
            <label>Server: </label><input id="serverName" type="text" placeholder="Server Name or Server IP ~">
            <button id="searchServer" name="{% url 'shell:index' %}">Search</button></div>
    </div>
    <table id="layout-table" border="1" cellspacing="0" cellpadding="6">
        <thead>
            <tr class="table_style">
                <th width=9%>ServerRoom</th>
                <th width=9%>GroupName</th>
                <th width=8%>ServerName</th>
                <th width=8%>IP</th>
                <th width=5%>User</th>
                <th width=9%>System</th>
                <th width=4%>CPU(core)</th>
                <th width=5%>Memory</th>
                <th width=5%>Disk</th>
                <th width="7%">Creator</th>
                <th width=16%>Action</th>
            </tr>
        </thead>
        <tbody id="tbody">
            {% for host in servers %}
                <tr>
                    <td>{{ host.room.name }} - {{ host.room.type|get_value_from_list:'room_type' }}</td>
                    <td>{{ host.group.name }}</td>
                    <td>{{ host.name }}</td>
                    <td style="text-align: center;">{{ host.host }}</td>
                    <td style="text-align: center;">{{ host.user }}</td>
                    <td>{{ host.system }}</td>
                    <td style="text-align: center;">{{ host.cpu }}</td>
                    <td style="text-align: center;">{{ host.mem }}G</td>
                    <td style="text-align: center;">{{ host.disk }}</td>
                    <td style="text-align: center;">{{ host.creator }}</td>
                    <td>
                        <a target="_blank" href="{% url 'shell:open_shell' %}?ip={{ host.host }}">OpenShell</a>
                        <a target="_self" href="{% url 'shell:package_home' %}?ip={{ host.host }}">Deploy</a>
                        {% if is_staff or operator == host.creator %}
                            <a onclick="edit_server('{{ host.id }}')">Edit</a>
                            <a href="" onclick="delete_server('{{ host.id }}')">Delete</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="myModal">
        <div class="modal-content">
            <div class="modal-header"><span class="close">&times;</span><h2 id="title-name">Add Server</h2></div>
            <div class="modal-body"><div class="modal-col" style="display: none;"><div class="label"><label>ID: </label></div>
                    <div class="input"><input id="ID" type="text" disabled readonly></div></div>
                <div class="modal-col"><div class="label"><label>GroupName: </label></div>
                    <div class="input"><select id="GroupName">
                            <option value="" selected></option>
                            {% for group in groups %}
                                <option value="{{ group.id }}">{{ group.name }}</option>
                            {% endfor %}
                        </select></div></div>
                <div class="modal-col"><div class="label"><label>ServerRoom: </label></div>
                    <div class="input"><select id="Server-room">
                            <option value=""></option>
                            {% for room in rooms %}
                                {% if room.id != '520' %}
                                    <option value="{{ room.id }}">{{ room.name }} - {{ room.type|get_value_from_list:'room_type' }}</option>
                                {% endif %}
                            {% endfor %}
                        </select></div></div>
                <div class="modal-col"><div class="label"><label>ServerName: </label></div><div class="input">
                    <input id="ServerName" type="text" placeholder="Please input server's name"></div></div>
                <div class="modal-col"><div class="label"><label>ServerIP: </label></div><div class="input">
                    <input id="ServerIP" type="text" placeholder="Please input server IP"></div></div>
                <div class="modal-col"><div class="label"><label>Port：</label></div><div class="input">
                    <input id="Port" type="text" value="22" placeholder="Please input server IP"></div></div>
                <div class="modal-col"><div class="label"><label>UserName：</label></div><div class="input">
                    <input id="UserName" type="text" value="root" placeholder="Please input server username"></div></div>
                <div class="modal-col"><div class="label"><label>Password：</label></div><div class="input">
                    <input id="Password" type="password" placeholder="Please input server password"></div></div>
            </div>
            <div class="modal-footer"><a class="cancel">Cancel</a><a class="submit">Submit</a></div></div></div>
    <div class="myModal">
        <div class="modal-content">
            <div class="modal-header"><span class="close">&times;</span><h2 id="title-name">Edit User</h2></div>
            <div class="modal-body"><div class="modal-col"><div class="label"><label>Operation: </label></div>
                    <div class="input"><select id="operator">
                            <option value="add">Add User to Group</option>
                            <option value="delete">Remove User from Group</option>
                        </select></div></div>
                <div class="modal-col"><div class="label"><label>GroupName: </label></div>
                    <div class="input"><select id="group_name_1">
                            <option value="" selected></option>
                            {% for group in groups %}
                                <option value="{{ group.id }}">{{ group.name }}</option>
                            {% endfor %}
                        </select></div></div>
                <div class="modal-col"><div class="label"><label>UserName：</label></div><div class="input">
                    <input id="user_name_1" type="text" placeholder="Please input username ~"></div></div>
            </div>
            <div class="modal-footer"><a class="cancel">Cancel</a><a class="submit">Submit</a></div></div></div>
    <div class="myModal">
        <div class="modal-content">
            <div class="modal-header"><span class="close">&times;</span><h2 id="title-name">Create Group</h2></div>
            <div class="modal-body"><div class="modal-col"><div class="label"><label>Operation: </label></div>
                    <div class="input"><select id="group_operator">
                            <option value="add">Add Group</option>
                            <option value="delete">Delete Group</option>
                        </select></div></div>
                <div class="modal-col" id="group_input"><div class="label"><label>GroupName：</label></div><div class="input">
                    <input id="group_name_2" type="text" placeholder="Please input group name ~"></div></div>
                <div class="modal-col" id="group_identifier"><div class="label"><label>Identifier：</label></div><div class="input">
                    <input id="group_identifier_2" type="text" placeholder="Please input group unique identifier ~"></div></div>
                <div class="modal-col" id="group_prefix"><div class="label"><label>Url Prefix：</label></div><div class="input">
                    <input id="url-prefix" type="text" placeholder="Please input url path prefix ~"></div></div>
                <div class="modal-col" id="group_select" style="display: none;"><div class="label"><label>GroupName：</label></div>
                    <div class="input"><select id="group_id" name="{% url 'shell:get_group' %}"></select></div></div></div>
            <div class="modal-footer"><a class="cancel">Cancel</a><a class="submit" name="{% url 'shell:create_group' %}">Submit</a></div>
        </div></div>
    <div class="myModal">
        <div class="modal-content">
            <div class="modal-header"><span class="close">&times;</span><h2 id="title-name">Create Server Room</h2></div>
            <div class="modal-body"><div class="modal-col"><div class="label"><label>Operation: </label></div>
                    <div class="input"><select id="room_operator">
                        <option value="add">Add Server Room</option>
                        <option value="delete">Delete Server Room</option>
                    </select></div></div>
                <div class="modal-col" id="room_input"><div class="label"><label>Name：</label></div><div class="input">
                    <input id="room_name" type="text" placeholder="Please input server room name ~"></div></div>
                <div class="modal-col" id="room_type_select"><div class="label"><label>Type: </label></div><div class="input">
                        <select id="room_type">
                            <option value="0" selected>Used to Applications</option>
                            <option value="1">Used to Middleware</option>
                            <option value="2">Used to Pressure Test</option>
                        </select></div></div>
                <div class="modal-col" id="room_id_select" style="display: none;"><div class="label"><label>ServerRoom: </label></div>
                    <div class="input"><select id="room_id" name="{% url 'shell:get_room' %}"></select></div></div></div>
            <div class="modal-footer"><a class="cancel">Cancel</a><a class="submit" name="{% url 'shell:create_room' %}">Submit</a></div>
        </div></div>
    <div class="modal_cover"><div class="modal_gif"></div></div>
{% endblock %}
{% block define_js %}
    {% compress js %}
    <script src="{% static 'shell/js/index.js' %}"></script>
    {% endcompress %}
    <script type="text/javascript">
    $(function () {
        PagingManage($("#paging"), {{ total_page }}, {{ page }}, '{% url 'shell:index' %}?pageSize=' + {{ page_size }} + '&page=')
    });
    </script>
{% endblock %}

shell/templates/packages.html
{% extends 'shell_home.html' %}
{% load static compress %}
{% load myFilter %}
{% block container2 %}
    <div id="filter">
        <div style="width: 30%; float: none;"><button id="upload-package">Upload Package</button></div>
        {% if servers %}
            <div>
                <span>Current Server <strong>{{ servers.host }}</strong>: System release version is
                    <strong style="color: red;">{{ servers.system }}</strong>, CPU architecture is
                    <strong style="color: red;">{{ servers.arch }}</strong>,
                    Please check system version and CPU Arch before you deploy package.
                </span>
            </div>
        {% endif %}
    </div>
    <table id="layout-table" border="1" cellspacing="0" cellpadding="6">
        <thead>
            <tr class="table_style">
                <th width=15%>Name</th>
                <th width=10%>Type</th>
                <th width=10%>System</th>
                <th width=10%>Arch</th>
                <th width=10%>Creator</th>
                <th width=12%>CreateTime</th>
                <th width=20%>Action</th>
            </tr>
        </thead>
        <tbody id="tbody">
            {% for package in packages %}
                <tr>
                    <td style="padding-left: 3px;">{{ package.name }}</td>
                    <td style="text-align: center;">{{ package.type }}</td>
                    <td style="text-align: center; color: red;">{{ package.system }}</td>
                    <td style="text-align: center; color: red;">{{ package.arch }}</td>
                    <td style="text-align: center;">{{ package.operator }}</td>
                    <td style="text-align: center;">{{ package.create_time | date:"Y-m-d H:i:s" }}</td>
                    <td>
                        {% if servers %}
                            <a onclick="deploy('{% url 'shell:deploy_package' %}', '{{ servers.host }}', '{{ package.id }}', '{{ package.system }}', '{{ package.arch }}')">Deploy</a>
                            <a onclick="stop_deploy('{% url 'shell:stop_package' %}', '{{ servers.host }}', '{{ package.id }}')">Uninstall</a>
                        {% endif %}
                        <a href="" onclick="delete_package('{% url 'shell:delete_package' %}', '{{ package.id }}')">Delete</a>

                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="myModal">
        <div class="modal-content">
            <div class="modal-header"><span class="close">&times;</span><h2 id="title-name">Upload Package</h2></div>
            <div class="modal-body">
                <div class="modal-col"><div class="label"><label>System: </label></div><div class="input">
                        <select id="system-version">
                            <option value="Ubuntu">Ubuntu</option>
                            <option value="CentOS">CentOS</option>
                            <option value="Debian">Debian</option>
                            <option value="RedHat">Red Hat</option>
                        </select></div></div>
                <div class="modal-col"><div class="label"><label>CPU Arch: </label></div><div class="input">
                        <select id="cpu-arch">
                            <option value="x86_64">X86 Arch 64bits</option>
                            <option value="x86">X86 Arch 32bits</option>
                            <option value="arm64">Arm Arch 64bits</option>
                            <option value="arm32">Arm Arch 32bits</option>
                            <option value="amd64">Amd Arch 64bits</option>
                            <option value="amd32">Amd Arch 32bits</option>
                        </select></div></div>
                <div class="modal-col"><div class="label"><label>Package Type: </label></div><div class="input">
                        <select id="agent-type">
                            <option value="monitor-agent">Monitor Agent</option>
                            <option value="jmeter-agent">JMeter Agent</option>
                            <option value="nginx-agent">Nginx Agent</option>
                            <option value="java">JAVA</option>
                            <option value="jmeter">JMeter</option>
                        </select></div></div></div>
            <div class="modal-footer"><a class="cancel">Cancel</a><a class="submit">Submit</a></div></div></div>
    <input type="file" name="filename" id="uploadpackage" accept=".zip, .tar.gz" style="display: none">
    <div class="modal_cover"><div class="modal_gif"></div></div>
{% endblock %}
{% block define_js %}
    {% compress js %}
    <script src="{% static 'shell/js/package.js' %}"></script>
    {% endcompress %}
    <script type="text/javascript">
        document.getElementsByClassName('home_list')[0].innerHTML = '<a href="{% url 'home' %}">Home</a><span>>></span><a href="{% url 'shell:index' %}">Shell</a><span>>></span><a href="{% url 'shell:package_home' %}">Package</a>';
    </script>
{% endblock %}