MyPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from user.views import home, course, register_first

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', home, name='home'),
    path('course', course, name='course'),
    path('register/first', register_first, name='register_first'),
    path('user/', include('user.urls'), name='user'),
    path('shell/', include('shell.urls'), name='shell'),
    path('monitor/', include('monitor.urls'), name='monitor'),
    path('performance/', include('performance.urls'), name='perf'),
]

urlpatterns = [
    path(f'{settings.PREFIX}/', include(urlpatterns))
]

performance/urls.py
from django.urls import path
from django.conf import settings
from . import views
from . import planViews
from . import taskViews
from . import threadViews
from . import controllerViews
from . import sampleViews
from . import headerViews
from . import jmeterViews

app_name = 'perf'
urlpatterns = [
    path('home', taskViews.home, name='home'),
    path('delete', views.delete, name='delete'),
    path('setStatus', views.is_valid, name='set_status'),

    path('plan', planViews.home, name='plan_home'),
    path('plan/add', planViews.add, name='plan_add'),
    path('plan/edit', planViews.edit, name='plan_edit'),
    path('plan/copy', planViews.copy_plan, name='plan_copy'),
    path('plan/file/upload', planViews.upload_file, name='plan_upload_file'),
    path('plan/variable', planViews.edit_variable, name='plan_variable'),

    path('task', taskViews.home, name='task_home'),
    # path('task/register', taskViews.register, name='agent_register'),
    path('task/status', taskViews.get_running_status, name='task_status'),
    path('task/add', taskViews.add_to_task, name='task_add'),
    path('task/delete', taskViews.delete_task, name='task_delete'),
    path('task/start', taskViews.start_task, name='task_start'),
    path('task/stop', taskViews.stop_task, name='task_stop'),
    path('task/download', taskViews.download_file, name='task_download'),
    path('task/download/log', taskViews.download_log, name='task_download_log'),
    path('task/change', taskViews.change_tps, name='change_tps'),
    # path('task/register/getMessage', taskViews.set_message, name='task_set_message'),
    path('task/query', taskViews.query_data, name='task_query'),
    path('task/detail', taskViews.view_task_detail, name='task_detail'),
    path('task/getIdleServer', taskViews.get_idle_server, name='get_idle_server'),
    path('task/getUsedServer', taskViews.get_used_server, name='get_used_server'),
    path('task/getRunningServer', taskViews.get_running_server, name='get_running_server'),
    path('task/autoRun', views.request_auto_run, name='auto_run_test'),
    # path('task/cancel', views)

    path('group', threadViews.home, name='group_home'),
    path('group/add', threadViews.add_group, name='group_add'),
    path('group/edit', threadViews.edit_group, name='group_edit'),
    path('group/copy', threadViews.copy_group, name='group_copy'),
    path('group/cookie', threadViews.edit_cookie, name='group_cookie'),
    path('group/file/upload', threadViews.upload_file, name='group_upload_file'),
    path('group/file/delete', threadViews.delete_file, name='group_delete_file'),

    path('controller', controllerViews.home, name='controller_home'),
    path('controller/add', controllerViews.add_group, name='controller_add'),
    path('controller/copy', controllerViews.copy_controller, name='controller_copy'),
    path('controller/edit', controllerViews.edit_group, name='controller_edit'),

    path('sample', sampleViews.home, name='sample_home'),
    path('sample/header', sampleViews.get_from_header, name='sample_header_home'),
    path('sample/add', sampleViews.add_sample, name='sample_add'),
    path('sample/edit', sampleViews.edit_sample, name='sample_edit'),
    path('sample/copy', sampleViews.copy_sample, name='sample_copy'),
    path('header/getByMehtod', sampleViews.get_header_by_method, name='get_header_by_method'),

    path('header', headerViews.home, name='header_home'),
    path('header/add', headerViews.add_header, name='header_add'),
    path('header/edit', headerViews.edit_header, name='header_edit'),
    path('header/copy', headerViews.copy_header, name='header_copy'),

    path('jmeter', jmeterViews.home, name='jmeter_home'),
    path('jmeter/edit', jmeterViews.edit, name='jmeter_edit'),
    path('jmeter/upload', jmeterViews.upload_file, name='jmeter_upload'),
    path('jmeter/start', jmeterViews.add_to_task, name='jmeter_add'),

] if settings.IS_PERF == 1 else []

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('changePwd', views.change_pwd, name='change_pwd')
]

performance/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: leeyoshinari

import os
import time
import logging
import traceback
from django.db.models.deletion import ProtectedError
from django.conf import settings
from .models import TestPlan, ThreadGroup, TransactionController
from .models import HTTPRequestHeader, HTTPSampleProxy, PerformanceTestTask
from .taskViews import start_test, stop_test, change_tps_test
from .common.fileController import delete_local_file
from common.Result import result
# Create your views here.


logger = logging.getLogger('django')


def delete_file_from_disk(file_path):
    path_list = file_path.split('/')
    if settings.FILE_STORE_TYPE == '0':
        try:
            file_folder = os.path.join(settings.FILE_ROOT_PATH, path_list[-2])
            file_local_path = os.path.join(file_folder, path_list[-1])
            os.remove(file_local_path)
            _ = delete_local_file(file_folder)
        except FileNotFoundError:
            logger.warning(f"FileNotFound: No such file: {file_path}")
    else:
        settings.MINIO_CLIENT.delete_file(path_list[-2], path_list[-1])


def delete(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            delete_type = request.POST.get('type')
            delete_id = request.POST.get('id')
            if delete_type == 'plan':
                plan = TestPlan.objects.get(id=delete_id)
                if plan.is_file == 1:
                    delete_file_from_disk(plan.file_path)
                plan.delete()
            if delete_type == 'group':
                group = ThreadGroup.objects.get(id=delete_id)
                if group.file:
                    file_path = group.file.get('file_path')
                    delete_file_from_disk(file_path)
                group.delete()
            if delete_type == 'controller':
                TransactionController.objects.get(id=delete_id).delete()
            if delete_type == 'sample':
                HTTPSampleProxy.objects.get(id=delete_id).delete()
            if delete_type == 'header':
                HTTPRequestHeader.objects.get(id=delete_id).delete()
            if delete_type == 'task':
                task = PerformanceTestTask.objects.get(id=delete_id)
                if task.path:
                    delete_file_from_disk(task.path)
                task.delete()
            logger.info(f'{delete_type} {delete_id} is deleted success, operator: {username}, IP: {ip}')
            return result(msg='Delete success ~')
        except ProtectedError:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Delete failure, because it is referenced through protected foreign keys ~')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Delete failure ~')


def is_valid(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            set_type = request.POST.get('set_type')
            set_id = request.POST.get('id')
            is_valid = request.POST.get('is_valid')
            if set_type == 'plan':
                res = TestPlan.objects.get(id=set_id)
            if set_type == 'group':
                res = ThreadGroup.objects.get(id=set_id)
            if set_type == 'controller':
                res = TransactionController.objects.get(id=set_id)
            if set_type == 'sample':
                res = HTTPSampleProxy.objects.get(id=set_id)
            res.is_valid = is_valid
            res.operator = username
            res.save()
            logger.info(f'{set_type} {set_id} status is set to {is_valid} success, operator: {username}, IP: {ip}')
            return result(msg='Set success ~')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Set failure ~')


def request_auto_run(request):
    if request.method == 'GET':
        username = request.user.username
        ip = request.headers.get('x-real-ip')
        tasks = PerformanceTestTask.objects.filter(plan__schedule=1, status=0)
        logger.info(f'Total auto test task is {len(tasks)}')
        for task in tasks:
            index = 0
            total_index = len(task.plan.time_setting) - 1
            for timing in task.plan.time_setting:
                if index == 0:
                    settings.SCHEDULER.add_job(start_test, 'date', run_date=timing['timing'], args=[task.id, None, username, ip], id=f"{task.id}_{index}")
                elif index == total_index:
                    settings.SCHEDULER.add_job(stop_test, 'date', run_date=timing['timing'], args=[task.id, 'all', username, ip], id=f"{task.id}_{index}")
                else:
                    settings.SCHEDULER.add_job(change_tps_test, 'date', run_date=timing['timing'], args=[task.id, 'all', timing['value'], username, ip], id=f"{task.id}_{index}")
        logger.info(f'Auto run performance test task success, operator: {username}, IP: {ip}')
        return result(msg='success')


# def cancel_auto_task(request):


performance/templates/task/detail.html
{% extends 'perf_home.html' %}
{% load static compress %}
{% load myFilter %}
{% block add_js %}
    {% compress js %}
    <script src="{% static 'performance/js/echarts.common.js' %}"></script>
    <script src="{% static 'performance/js/visualize.js' %}"></script>
    <script src="{% static 'performance/js/task.js' %}"></script>
    {% endcompress %}
{% endblock %}
{% block navigate %}
    <a href="{% url 'perf:task_home' %}">Test Task</a>
{% endblock %}
{% block detail_action %}
    {% if tasks %}
    <div style="height: 50px;"><div><h3>Test Plan Name:
                <span><a href="{% url 'perf:plan_home' %}?keyWord={{ tasks.plan.name }}">{{ tasks.plan.name }}</a></span>
                <span style="margin-left: 10%; color: {{ tasks.status | get_value_from_list:'task_color' }}">{{ tasks.status | get_value_from_list:'task_status' }}</span></h3>
            <span style="float: right; margin-right: 30px; width: 110px;"><a target="_blank" href="{{ tasks.path }}">Download File</a></span>
            {% if tasks.status == 1 %}
                <span style="float: right; margin-right: 30px; width: 42px;"><a href="#" onclick="stop_test('{% url 'perf:task_stop' %}', {{ tasks.id }}, 'all')">Stop</a></span>
            {% endif %}
            {% if tasks.plan.type == 1 and tasks.status == 1 %}
                <span style="float: right; margin-right: 30px; width: 100px;"><a onclick="change_tps('{% url 'perf:change_tps' %}', {{ tasks.id }}, 'all')">Change TPS</a></span>
            {% endif %}
        </div></div>
    <div style="height: 50px; margin-left: 3%;"><div class="plan-detail">
            {% if tasks.plan.type == 0 %}
                <label>Fixed Thread Num: </label><span>{{ tasks.plan.target_num }}</span>
            {% else %}
                <label>Target TPS: </label><span>{{ tasks.plan.target_num }}/s</span>
            {% endif %}
        </div>
        {% if tasks.status == 1 %}
            <div class="plan-detail">
        {% else %}
            <div class="plan-detail" style="display: none;">
        {% endif %}
                <label>Current TPS: </label><span>{{ tasks.plan.duration }}/s</span></div>
        <div class="plan-detail"><label>StartTime: </label><span>{{ tasks.start_time | date:"Y-m-d H:i:s" }}</span></div>
        {% if tasks.status > 1 %}
            <div class="plan-detail">
        {% else %}
            <div class="plan-detail" style="display: none;">
        {% endif %}
            <label>EndTime: </label><span>{{ tasks.end_time | date:"Y-m-d H:i:s" }}</span></div></div>
    <div style="height: 50px; margin-left: 3%;"><div class="plan-detail"><label>Samples: </label><span>{{ tasks.samples }}</span></div>
        <div class="plan-detail"><label>Average TPS: </label><span>{{ tasks.tps }}/s</span></div>
        <div class="plan-detail"><label>RT(avg): </label><span>{{ tasks.average_rt }} ms</span></div>
        <div class="plan-detail"><label>RT(min): </label><span>{{ tasks.min_rt }} ms</span></div>
        <div class="plan-detail"><label>RT(max): </label><span>{{ tasks.max_rt }} ms</span></div>
        <div class="plan-detail"><label>Error(%): </label><span>{{ tasks.error }}%</span></div></div>
    {% endif %}
{% endblock %}
{% block other_content %}
    {% if tasks %}
    <div><h3 style="float: left;">Monitor Figure</h3>
        <input id="figure-title" type="text" value="(All Servers)" name="all" style="border: none; margin-left: 1%; vertical-align: bottom; background-color: white;" disabled readonly>
        <input id="start-time" type="text" value="{{ tasks.start_time | date:"Y-m-d H:i:s" }}" style="display: none;">
    </div><div id="figure" style="width: 100%;height:480px;margin: 0 auto;"></div>
    <div style="margin-top: 20px;"><h3>Pressure Server <span id="total-server" style="font-size: medium; font-weight: normal;"></span></h3>
        <div style="float: right; margin-right: 30px;"><a id="view-all" title="View all servers summary data." style="text-decoration: none; cursor: pointer; color: blue; margin-right: 20px;">View All</a>
            {% if tasks.status == 1 %}
                <a id="show-server" title="View idle servers." style="text-decoration: none; cursor: pointer; color: blue; margin-right: 20px;">Show More</a>
            {% endif %}
        </div></div>
    <div class="myModal"><div class="modal-content">
            <div class="modal-header"><span class="close">&times;</span><h2 id="title-name" style="margin-top: 3%;">Change Total TPS to</h2></div>
            <div class="modal-body"><div class="modal-col"><div class="label"><label>TPS Ratio(%)：</label></div>
                <div class="input"><input id="tps-ratio" type="number" name="{{ tasks.plan.target_num }}" placeholder="Please input TPS ratio (%)" style="width: 66%;"></div></div></div>
            <div class="modal-footer"><a class="cancel">Cancel</a><a class="submit">Submit</a></div></div></div>
    {% endif %}
{% endblock %}
{% block table_head %}
    {% if tasks %}
    <tr class="table_style">
        <th width="15%">Server</th>
        <th width="8%">TPS(/s)</th>
        <th width="10%">CPU</th>
        <th width="10%">Memory</th>
        <th width="10%">Disks</th>
        <th width="8%">Network</th>
        <th width="21%">Actions</th>
    </tr>
    {% endif %}
{% endblock %}
{% block table_body %}
{% endblock %}
{% block back_body %}
    <div style="margin-bottom: 3%;"></div>
{% endblock %}
{% block fenye %}
{% endblock %}
{% block backjs %}
{% endblock %}
{% block define_js %}
    {% if tasks %}
    <script type="text/javascript">
        let W = window.screen.width;
        document.getElementsByClassName('toolbar')[0].style.width = (W - 200) + 'px';
        document.getElementsByClassName('detail')[0].style.width = (W * 0.99 - 200) + 'px';
        $('#figure').removeAttr("_echarts_instance_").empty();
        let figure = document.getElementById('figure');
        let myChart = echarts.init(figure);
        plot(myChart, {{ tasks.id }}, '{% url 'perf:task_query' %}');
        {% if tasks.status > 1 %}
            get_used_server({{ tasks.id }}, '{% url 'perf:get_used_server' %}', '{% url 'perf:task_download_log' %}');
        {% else %}
            get_running_server({{ tasks.id }}, '{% url 'perf:get_running_server' %}', {{ tasks.status }}, '{% url 'perf:task_start' %}',
                '{% url 'perf:change_tps' %}', '{% url 'perf:task_download_log' %}', '{% url 'perf:task_query' %}', '{% url 'perf:task_stop' %}', {{ tasks.plan.type }});
        {% endif %}
        {% if tasks.status == 1 %}
            let timer = setInterval(function () {plot_delta(myChart, {{ tasks.id }}, '{% url 'perf:task_query' %}')}, 10000);
            let query_server_timer = setInterval(function () {
                get_running_server({{ tasks.id }}, '{% url 'perf:get_running_server' %}', {{ tasks.status }}, '{% url 'perf:task_start' %}',
                '{% url 'perf:change_tps' %}', '{% url 'perf:task_download_log' %}', '{% url 'perf:task_query' %}', '{% url 'perf:task_stop' %}', {{ tasks.plan.type }})
            }, 5000);
            document.getElementById('show-server').addEventListener('click', function () {
                let title = document.getElementById('show-server').innerText;
                if (title === 'Show More') {
                    get_idle_server({{ tasks.server_room.id }}, '{% url 'perf:get_idle_server' %}', {{ tasks.id }}, '{% url 'perf:task_start' %}');
                    document.getElementById('show-server').innerText = "Show Less";
                } else {
                    let trs = document.getElementById('tbody').getElementsByClassName('idling');
                    let trs_length = trs.length;
                    for(let i=0; i<trs_length; i++) {
                        trs[0].remove();
                    }
                    document.getElementById('show-server').innerText = "Show More";
                }
            })
        {% endif %}
        document.getElementById('view-all').addEventListener('click', function () {
            let figure_title = document.getElementById('figure-title');
            figure_title.value = '(All Servers)';
            figure_title.name = 'all';
            plot(myChart, {{ tasks.id }}, '{% url 'perf:task_query' %}');
        })
        function view_host_figure(host) {
            let figure_title = document.getElementById('figure-title');
            figure_title.value = '(' + host + ')';
            figure_title.name = host;
            plot(myChart, {{ tasks.id }}, '{% url 'perf:task_query' %}');
        }
    </script>
    {% else %}
    <script type="text/javascript">
        $.Toast('Task is in starting, please wait a minute ~', 'warning');
    </script>
    {% endif %}
{% endblock %}

performance/templates/task/home.html
{% extends 'perf_home.html' %}
{% load static compress %}
{% load myFilter %}
{% block add_js %}
    {% compress js %}
    <script src="{% static 'performance/js/plan.js' %}"></script>
    {% endcompress %}
{% endblock %}
{% block navigate %}
    <a href="{% url 'perf:plan_home' %}">Test Plan</a>
{% endblock %}
{% block detail_action %}
{% endblock %}
{% block searchBlock %}
{% endblock %}
{% block table_head %}
    <tr class="table_style">
        <th width="11%">Plan Name</th>
        <th width="9%">Server Room</th>
        <th width="8%">Status</th>
        <th width="8%">Schedule</th>
        <th width="8%"># Samples</th>
        <th width="8%">Average(RT)</th>
        <th width="8%">TPS(/s)</th>
        <th width="8%">Error(%)</th>
        <th width="10%">Start Time</th>
        <th width="8%">Operator</th>
        <th width="15%">Actions</th>
    </tr>
{% endblock %}
{% block table_body %}
    {% for task in tasks %}
        <tr>
            {% if task.plan.is_file == 1 %}
                <td title="{{ task.plan.comment }}"><a href="{% url 'perf:jmeter_home' %}?keyWord={{ task.plan.name }}">{{ task.plan.name }}</a></td>
            {% else %}
                <td title="{{ task.plan.comment }}"><a href="{% url 'perf:plan_home' %}?keyWord={{ task.plan.name }}">{{ task.plan.name }}</a></td>
            {% endif %}
            <td title="{{ task.server_room.name }}" style="text-align: center;">{{ task.server_room.name }}</td>
            <td style="text-align: center;"><div class="round" style="background-color: {{ task.status | get_value_from_list:'task_color' }};"></div>{{ task.status | get_value_from_list:'task_status' }}</td>
            <td style="text-align: center;">{{ task.plan.schedule | get_value_from_list:'plan_schedule' }}</td>
            <td style="text-align: center;">{{ task.samples }}</td>
            <td style="text-align: center;">{{ task.average_rt }} ms</td>
            <td style="text-align: center;">{{ task.tps }}</td>
            <td style="text-align: center;">{{ task.error }} %</td>
            <td title="{{ task.start_time | date:"Y-m-d H:i:s" }}" style="text-align: center;">{{ task.start_time | date:"Y-m-d H:i:s" }}</td>
            <td title="{{ task.operator }}" style="text-align: center;">{{ task.operator }}</td>
            <td>
                {% if task.status < 4 %}
                    {% if task.status == 0 and task.plan.schedule == 0 %}
                        <a href="#" onclick="start_task('{% url 'perf:task_start' %}', {{ task.id }}, '{% url 'perf:task_status' %}', '{% url 'perf:task_detail' %}')">Start</a>
                    {% else %}
                        {% if task.status == 0 and task.plan.schedule == 1 %}
                            <a href="#">View</a>
                        {% else %}
                            <a href="{% url 'perf:task_detail' %}?id={{ task.id }}">View</a>
                        {% endif %}
                        {% if task.status == 1 %}
                            <a href="#" onclick="stop_task('{% url 'perf:task_stop' %}?id={{ task.id }}')">Stop</a>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <a href="#" onclick="Delete('{% url 'perf:delete' %}', '{% url 'perf:task_home' %}', 'task', {{ task.id }})">Delete</a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}
{% block define_js %}
    <script type="text/javascript">
        PagingManage($('#paging'), {{ total_page }}, {{ page }}, '{% url 'perf:task_home' %}?page=');
    </script>
{% endblock %}