MyPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from user.views import home, course, register_first

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', home, name='home'),
    path('course', course, name='course'),
    path('register/first', register_first, name='register_first'),
    path('user/', include('user.urls'), name='user'),
    path('shell/', include('shell.urls'), name='shell'),
    path('monitor/', include('monitor.urls'), name='monitor'),
    path('performance/', include('performance.urls'), name='perf'),
]

urlpatterns = [
    path(f'{settings.PREFIX}/', include(urlpatterns))
]

performance/urls.py
from django.urls import path
from django.conf import settings
from . import views
from . import planViews
from . import taskViews
from . import threadViews
from . import controllerViews
from . import sampleViews
from . import headerViews
from . import jmeterViews

app_name = 'perf'
urlpatterns = [
    path('home', taskViews.home, name='home'),
    path('delete', views.delete, name='delete'),
    path('setStatus', views.is_valid, name='set_status'),

    path('plan', planViews.home, name='plan_home'),
    path('plan/add', planViews.add, name='plan_add'),
    path('plan/edit', planViews.edit, name='plan_edit'),
    path('plan/copy', planViews.copy_plan, name='plan_copy'),
    path('plan/file/upload', planViews.upload_file, name='plan_upload_file'),
    path('plan/variable', planViews.edit_variable, name='plan_variable'),

    path('task', taskViews.home, name='task_home'),
    # path('task/register', taskViews.register, name='agent_register'),
    path('task/status', taskViews.get_running_status, name='task_status'),
    path('task/add', taskViews.add_to_task, name='task_add'),
    path('task/delete', taskViews.delete_task, name='task_delete'),
    path('task/start', taskViews.start_task, name='task_start'),
    path('task/stop', taskViews.stop_task, name='task_stop'),
    path('task/download', taskViews.download_file, name='task_download'),
    path('task/download/log', taskViews.download_log, name='task_download_log'),
    path('task/change', taskViews.change_tps, name='change_tps'),
    # path('task/register/getMessage', taskViews.set_message, name='task_set_message'),
    path('task/query', taskViews.query_data, name='task_query'),
    path('task/detail', taskViews.view_task_detail, name='task_detail'),
    path('task/getIdleServer', taskViews.get_idle_server, name='get_idle_server'),
    path('task/getUsedServer', taskViews.get_used_server, name='get_used_server'),
    path('task/getRunningServer', taskViews.get_running_server, name='get_running_server'),
    path('task/autoRun', views.request_auto_run, name='auto_run_test'),
    # path('task/cancel', views)

    path('group', threadViews.home, name='group_home'),
    path('group/add', threadViews.add_group, name='group_add'),
    path('group/edit', threadViews.edit_group, name='group_edit'),
    path('group/copy', threadViews.copy_group, name='group_copy'),
    path('group/cookie', threadViews.edit_cookie, name='group_cookie'),
    path('group/file/upload', threadViews.upload_file, name='group_upload_file'),
    path('group/file/delete', threadViews.delete_file, name='group_delete_file'),

    path('controller', controllerViews.home, name='controller_home'),
    path('controller/add', controllerViews.add_group, name='controller_add'),
    path('controller/copy', controllerViews.copy_controller, name='controller_copy'),
    path('controller/edit', controllerViews.edit_group, name='controller_edit'),

    path('sample', sampleViews.home, name='sample_home'),
    path('sample/header', sampleViews.get_from_header, name='sample_header_home'),
    path('sample/add', sampleViews.add_sample, name='sample_add'),
    path('sample/edit', sampleViews.edit_sample, name='sample_edit'),
    path('sample/copy', sampleViews.copy_sample, name='sample_copy'),
    path('header/getByMehtod', sampleViews.get_header_by_method, name='get_header_by_method'),

    path('header', headerViews.home, name='header_home'),
    path('header/add', headerViews.add_header, name='header_add'),
    path('header/edit', headerViews.edit_header, name='header_edit'),
    path('header/copy', headerViews.copy_header, name='header_copy'),

    path('jmeter', jmeterViews.home, name='jmeter_home'),
    path('jmeter/edit', jmeterViews.edit, name='jmeter_edit'),
    path('jmeter/upload', jmeterViews.upload_file, name='jmeter_upload'),
    path('jmeter/start', jmeterViews.add_to_task, name='jmeter_add'),

] if settings.IS_PERF == 1 else []

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('changePwd', views.change_pwd, name='change_pwd')
]

performance/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: leeyoshinari

import os
import time
import logging
import traceback
from django.db.models.deletion import ProtectedError
from django.conf import settings
from .models import TestPlan, ThreadGroup, TransactionController
from .models import HTTPRequestHeader, HTTPSampleProxy, PerformanceTestTask
from .taskViews import start_test, stop_test, change_tps_test
from .common.fileController import delete_local_file
from common.Result import result
# Create your views here.


logger = logging.getLogger('django')


def delete_file_from_disk(file_path):
    path_list = file_path.split('/')
    if settings.FILE_STORE_TYPE == '0':
        try:
            file_folder = os.path.join(settings.FILE_ROOT_PATH, path_list[-2])
            file_local_path = os.path.join(file_folder, path_list[-1])
            os.remove(file_local_path)
            _ = delete_local_file(file_folder)
        except FileNotFoundError:
            logger.warning(f"FileNotFound: No such file: {file_path}")
    else:
        settings.MINIO_CLIENT.delete_file(path_list[-2], path_list[-1])


def delete(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            delete_type = request.POST.get('type')
            delete_id = request.POST.get('id')
            if delete_type == 'plan':
                plan = TestPlan.objects.get(id=delete_id)
                if plan.is_file == 1:
                    delete_file_from_disk(plan.file_path)
                plan.delete()
            if delete_type == 'group':
                group = ThreadGroup.objects.get(id=delete_id)
                if group.file:
                    file_path = group.file.get('file_path')
                    delete_file_from_disk(file_path)
                group.delete()
            if delete_type == 'controller':
                TransactionController.objects.get(id=delete_id).delete()
            if delete_type == 'sample':
                HTTPSampleProxy.objects.get(id=delete_id).delete()
            if delete_type == 'header':
                HTTPRequestHeader.objects.get(id=delete_id).delete()
            if delete_type == 'task':
                task = PerformanceTestTask.objects.get(id=delete_id)
                if task.path:
                    delete_file_from_disk(task.path)
                task.delete()
            logger.info(f'{delete_type} {delete_id} is deleted success, operator: {username}, IP: {ip}')
            return result(msg='Delete success ~')
        except ProtectedError:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Delete failure, because it is referenced through protected foreign keys ~')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Delete failure ~')


def is_valid(request):
    if request.method == 'POST':
        try:
            username = request.user.username
            ip = request.headers.get('x-real-ip')
            set_type = request.POST.get('set_type')
            set_id = request.POST.get('id')
            is_valid = request.POST.get('is_valid')
            if set_type == 'plan':
                res = TestPlan.objects.get(id=set_id)
            if set_type == 'group':
                res = ThreadGroup.objects.get(id=set_id)
            if set_type == 'controller':
                res = TransactionController.objects.get(id=set_id)
            if set_type == 'sample':
                res = HTTPSampleProxy.objects.get(id=set_id)
            res.is_valid = is_valid
            res.operator = username
            res.save()
            logger.info(f'{set_type} {set_id} status is set to {is_valid} success, operator: {username}, IP: {ip}')
            return result(msg='Set success ~')
        except:
            logger.error(traceback.format_exc())
            return result(code=1, msg='Set failure ~')


def request_auto_run(request):
    if request.method == 'GET':
        username = request.user.username
        ip = request.headers.get('x-real-ip')
        tasks = PerformanceTestTask.objects.filter(plan__schedule=1, status=0)
        logger.info(f'Total auto test task is {len(tasks)}')
        for task in tasks:
            index = 0
            total_index = len(task.plan.time_setting) - 1
            for timing in task.plan.time_setting:
                if index == 0:
                    settings.SCHEDULER.add_job(start_test, 'date', run_date=timing['timing'], args=[task.id, None, username, ip], id=f"{task.id}_{index}")
                elif index == total_index:
                    settings.SCHEDULER.add_job(stop_test, 'date', run_date=timing['timing'], args=[task.id, 'all', username, ip], id=f"{task.id}_{index}")
                else:
                    settings.SCHEDULER.add_job(change_tps_test, 'date', run_date=timing['timing'], args=[task.id, 'all', timing['value'], username, ip], id=f"{task.id}_{index}")
        logger.info(f'Auto run performance test task success, operator: {username}, IP: {ip}')
        return result(msg='success')


# def cancel_auto_task(request):


performance/templates/threadGroup/add.html
{% extends 'perf_home.html' %}
{% load static compress %}
{% block add_js %}
    {% compress js %}
    <script src="{% static 'performance/js/group.js' %}"></script>
    {% endcompress %}
{% endblock %}
{% block navigate %}
    {% if plan_id %}
        <a href="{% url 'perf:group_home' %}?id={{ plan_id }}">Thread Group</a>
    {% else %}
        <a href="{% url 'perf:group_home' %}">Thread Group</a>
    {% endif %}
    <span>>></span><span>Add Thread Group</span>
{% endblock %}
{% block detail %}
    <div class="list-body">
        <div class="row-cols"><div class="label-div"><label>Plan ID: </label></div>
            <div class="value-div"><select id="planid">
                    {% for foo in plans %}
                        {% if foo.id == plan_id %}
                            <option value="{{ foo.id }}" selected>{{ foo.name }}</option>
                        {% else %}
                            <option value="{{ foo.id }}">{{ foo.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select></div></div>
        <div class="row-cols"><div class="label-div"><label>Name:</label></div>
            <div class="value-div"><input type="text" id="name" placeholder="Please input name ~"></div></div>
        <div class="row-cols"><div class="label-div">
            <div class="helpstyle"><span data-tooltip="Ramp-up period (seconds). Only TPS Type valid.">?</span></div><label>Ramp Time:</label></div>
            <div class="value-div"><input type="text" id="ramp_time" placeholder="Please input ramp time ~" value="1"></div></div>
        <div class="row-cols"><div class="label-div">
            <div class="helpstyle"><span data-tooltip="CSV Data Set Config, that stores variables used during running.">?</span></div><label>CSVDataSet:</label></div>
            <div class="value-div">
                <button id="upload_file" onclick="upload_file('{% url 'perf:group_upload_file' %}');" style="width: 10%;">Upload File</button>
                <button id="download_file" onclick="download_file()" style="width: 11%; display: none;">Download File</button>
                <button id="delete_file" onclick="delete_file('{% url 'perf:group_delete_file' %}', '')" style="width: 10%; display: none;">Delete File</button>
                <input type="file" id="fileUpload-input" accept=".xls,.xlsx,.csv,.txt" style="display: none;">
                <input type="text" id="file_path" name="" value="" readonly style="width: 22%; margin-left: 2%; border: none; background-color: white;" disabled></div>
            <div class="small-div" style="display:none;"><div class="label">
                <div class="helpstyle"><span data-tooltip="Variable Names (comma-delimited). Each variable corresponds to each column in the CSV file.">?</span></div><label>Variable Names:</label></div>
                <input type="text" id="variable_names" placeholder="Please input variable names, split by ',' ~"></div>
            <div class="small-div" style="display:none;"><div class="label">
                <div class="helpstyle"><span data-tooltip="Delimiter (use '\t' for tab)">?</span></div><label>Delimiter:</label></div>
                <input type="text" id="delimiter" placeholder="Please input delimiter ~" value=","></div>
            <div class="small-div" style="display:none;"><div class="label">
                <div class="helpstyle"><span data-tooltip="Recycle on EOF ? True: recycle when EOF. False: stop when EOF.">?</span></div><label>Recycle:</label></div>
                <select id="recycle">
                    <option value="true">True</option>
                    <option value="false">False</option>
                </select></div>
            <div class="small-div" style="display:none;"><div class="label">
                <div class="helpstyle"><span data-tooltip="Threads Sharing mode">?</span></div><label>Share Mode:</label></div>
                <select id="share_mode">
                    {% for k, v in share_mode.items %}
                        <option value="{{ v }}">{{ k}}</option>
                    {% endfor %}
                </select></div></div>
        <div class="row-cols"><div class="label-div"><label>Comment:</label></div>
            <div class="value-div"><input type="text" id="comment" placeholder="Please input thread group comment ~"></div></div></div>
    <div class="list-footer"><div>
            {% if plan_id %}
                <a href="{% url 'perf:group_home' %}?id={{ plan_id }}">Cancel</a>
                <a href="#" onclick="save_group('{% url 'perf:group_add' %}', '{% url 'perf:group_home' %}', {{ plan_id }})">Submit</a>
            {% else %}
                <a href="{% url 'perf:group_home' %}">Cancel</a>
                <a href="#" onclick="save_group('{% url 'perf:group_add' %}', '{% url 'perf:group_home' %}', '')">Submit</a>
            {% endif %}
        </div></div>
{% endblock %}

performance/templates/threadGroup/edit.html
{% extends 'perf_home.html' %}
{% load static compress %}
{% load myFilter %}
{% block add_js %}
    {% compress js %}
    <script src="{% static 'performance/js/group.js' %}"></script>
    {% endcompress %}
{% endblock %}
{% block navigate %}
    <a href="{% url 'perf:group_home' %}?id={{ groups.plan_id }}">Thread Group</a><span>>></span><span>Edit Thread Group</span>
{% endblock %}
{% block detail %}
    <div class="list-body">
        <div class="row-cols"><div class="label-div"><label>ID:</label></div>
            <div class="value-div"><input type="text" id="ID" readonly value="{{ groups.id }}" disabled></div></div>
        <div class="row-cols"><div class="label-div"><label>Plan ID: </label></div>
            <div class="value-div"><select id="planid">
                    {% for foo in plans %}
                        {% if foo.id == groups.plan_id %}
                            <option value="{{ foo.id }}" selected>{{ foo.name }}</option>
                        {% else %}
                            <option value="{{ foo.id }}">{{ foo.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select></div></div>
        <div class="row-cols"><div class="label-div"><label>Name:</label></div>
            <div class="value-div"><input type="text" id="name" placeholder="Please input name ~" value="{{ groups.name }}"></div></div>
        <div class="row-cols"><div class="label-div"><div class="helpstyle"><span data-tooltip="Ramp-up period (seconds). Only TPS Type valid.">?</span></div><label>Ramp Time:</label></div>
            <div class="value-div"><input type="text" id="ramp_time" placeholder="Please input ramp time ~" value="{{ groups.ramp_time }}"></div></div>
        <div class="row-cols"><div class="label-div"><div class="helpstyle"><span data-tooltip="CSV Data Set Config, that stores variables used during running.">?</span></div><label>CSVDataSet:</label></div>
            {% if groups.file %}
                <div class="value-div">
                    <button id="upload_file" onclick="upload_file('{% url 'perf:group_upload_file' %}');" style="width: 10%;">Upload File</button>
                    <button id="download_file" onclick="download_file()" style="width: 11%;">Download File</button>
                    <button id="delete_file" onclick="delete_file('{% url 'perf:group_delete_file' %}', '{{ groups.id }}')" style="width: 10%;">Delete File</button>
                    <input type="file" id="fileUpload-input" accept=".xls,.xlsx,.csv,.txt" style="display: none;">
                    <input type="text" id="file_path" name="{{ groups.file.file_path }}" value="{{ groups.file.file_path | parse_url_name }}" readonly style="width: 16%; margin-left: 2%; border: none; background-color: white;" disabled>
                </div><div class="small-div"><div class="label">
                    <div class="helpstyle"><span data-tooltip="Variable Names (comma-delimited). Each variable corresponds to each column in the CSV file.">?</span></div>
                    <label>Variable Names:</label></div>
                    <input type="text" id="variable_names" placeholder="Please input variable names, split by ',' ~" value="{{ groups.file.variable_names }}">
                </div><div class="small-div"><div class="label">
                    <div class="helpstyle"><span data-tooltip="Delimiter (use '\t' for tab)">?</span></div>
                    <label>Delimiter:</label></div>
                    <input type="text" id="delimiter" placeholder="Please input delimiter ~" value="{{ groups.file.delimiter }}">
                </div><div class="small-div"><div class="label">
                    <div class="helpstyle"><span data-tooltip="Recycle on EOF ? True: recycle when EOF. False: stop when EOF.">?</span></div>
                    <label>Recycle:</label></div><select id="recycle">
                        {% if groups.file.recycle == 'true' %}
                            <option value="true" selected>True</option>
                            <option value="false">False</option>
                        {% else %}
                            <option value="true">True</option>
                            <option value="false" selected>False</option>
                        {% endif %}
                    </select></div>
                <div class="small-div"><div class="label"><div class="helpstyle"><span data-tooltip="Threads Sharing mode">?</span></div><label>Share Mode:</label></div><select id="share_mode">
                        {% for k, v in share_mode.items %}
                            {% if v == groups.file.share_mode %}
                                <option value="{{ v }}" selected>{{ k}}</option>
                            {% else %}
                                <option value="{{ v }}">{{ k}}</option>
                            {% endif %}
                        {% endfor %}
                    </select></div>
            {% else %}
                <div class="value-div">
                    <button id="upload_file" onclick="upload_file('{% url 'perf:group_upload_file' %}');" style="width: 10%;">Upload File</button>
                    <button id="download_file" onclick="download_file('{% static 'files/' %}')" style="width: 11%; display: none;">Download File</button>
                    <button id="delete_file" onclick="delete_file('{% url 'perf:group_delete_file' %}', '{{ groups.id }}')" style="width: 10%; display: none;">Delete File</button>
                    <input type="file" id="fileUpload-input" accept=".xls,.xlsx,.csv,.txt" style="display: none;">
                    <input type="text" id="file_path" value="" readonly style="width: 16%; margin-left: 2%; border: none; background-color: white;" disabled>
                </div><div class="small-div" style="display:none;"><div class="label">
                    <div class="helpstyle"><span data-tooltip="Variable Names (comma-delimited). Each variable corresponds to each column in the CSV file.">?</span></div>
                    <label>Variable Names:</label></div>
                    <input type="text" id="variable_names" placeholder="Please input variable names, split by ',' ~"></div>
                <div class="small-div" style="display:none;"><div class="label">
                    <div class="helpstyle"><span data-tooltip="Delimiter (use '\t' for tab)">?</span></div>
                    <label>Delimiter:</label></div>
                    <input type="text" id="delimiter" placeholder="Please input delimiter ~" value=","></div>
                <div class="small-div" style="display:none;"><div class="label">
                    <div class="helpstyle"><span data-tooltip="Recycle on EOF ? True: recycle when EOF. False: stop when EOF.">?</span></div>
                    <label>Recycle:</label></div>
                    <select id="recycle">
                        <option value="true">True</option>
                        <option value="false">False</option>
                    </select></div>
                <div class="small-div" style="display:none;"><div class="label">
                    <div class="helpstyle"><span data-tooltip="Threads Sharing mode">?</span></div><label>Share Mode:</label></div>
                    <select id="share_mode">
                        <{% for k, v in share_mode.items %}
                            <option value="{{ v }}">{{ k}}</option>
                        {% endfor %}
                    </select></div>
            {% endif %}
        </div><div class="row-cols"><div class="label-div"><label>Comment:</label></div><div class="value-div">
            <input type="text" id="comment" placeholder="Please input thread group comment ~" value="{{ groups.comment }}"></div></div></div>
    <div class="list-footer"><div><a href="{% url 'perf:group_home' %}?id={{ groups.plan_id }}">Cancel</a>
        <a href="#" onclick="edit_group('{% url 'perf:group_edit' %}', '{% url 'perf:group_home' %}', {{ groups.plan_id }})">Submit</a></div></div>
{% endblock %}

performance/templates/threadGroup/home.html
{% extends 'perf_home.html' %}
{% load static compress %}
{% block add_js %}
    {% compress js %}
    <script src="{% static 'performance/js/group.js' %}"></script>
    {% endcompress %}
{% endblock %}
{% block navigate %}
    {% if plan_id %}
        <a href="{% url 'perf:group_home' %}?id={{ plan_id }}">Thread Group</a>
    {% else %}
        <a href="{% url 'perf:group_home' %}">Thread Group</a>
    {% endif %}
{% endblock %}
{% block detail_action %}
    {% if plan_id %}
        <a href="{% url 'perf:group_add' %}?id={{ plan_id }}">Add Thread Group</a>
    {% else %}
        <a href="{% url 'perf:group_add' %}">Add Thread Group</a>
    {% endif %}
{% endblock %}
{% block searchBlock %}
    <div class="search">
        {% if key_word %}
            <input type="text" id="searching" placeholder="Please input key words ~" value="{{ key_word }}">
        {% else %}
            <input type="text" id="searching" placeholder="Please input key words ~">
        {% endif %}
        {% if plan_id %}
            <button onclick="search('{% url 'perf:group_home' %}?id={{ plan_id }}')">Search</button>
        {% else %}
            <button onclick="search('{% url 'perf:group_home' %}')">Search</button>
        {% endif %}
    </div>
{% endblock %}
{% block table_head %}
    <tr class="table_style">
        <th width="10%">Plan Name</th>
        <th width="10%">Name</th>
        <th width="17%">Comment</th>
        <th width="12%">Create Time</th>
        <th width="12%">Update Time</th>
        <th width="9%">Operator</th>
        <th width="30%">Actions</th>
    </tr>
{% endblock %}
{% block table_body %}
    {% for group in groups %}
        {% if group.is_valid == 'false' %}
            <tr style="background-color: white">
        {% else %}
            <tr>
        {% endif %}
            <td title="{{ group.plan.name }}"><a href="{% url 'perf:plan_home' %}?keyWord={{ group.plan.name }}">{{ group.plan.name }}</a></td>
            <td style="text-align: center;" title="{{ group.name }}"><a href="{% url 'perf:group_home' %}?id={{ group.plan.id }}">{{ group.name }}</a></td>
            <td title="{{ group.comment }}">{{ group.comment }}</td>
            <td style="text-align: center;">{{ group.create_time | date:"Y-m-d H:i:s" }}</td>
            <td style="text-align: center;">{{ group.update_time | date:"Y-m-d H:i:s" }}</td>
            <td style="text-align: center;">{{ group.operator }}</td>
            <td>
                {% if group.is_valid == 'true' %}
                    <a href="{% url 'perf:group_edit' %}?id={{ group.id }}">Edit</a>
                    <a href="#" onclick="set_status('group', '{{ group.id }}', 'false', '{% url 'perf:set_status' %}')">Disabled</a>
                    <a href="{% url 'perf:group_copy' %}?id={{ group.id }}&plan_id={{ group.plan.id }}">Copy</a>
                    <a title="Set cookies of the ThreadGroup, It is optional" href="{% url 'perf:group_cookie' %}?id={{ group.id }}">Cookies</a>
                    <a title="View Controllers of the ThreadGroup" href="{% url 'perf:controller_home' %}?id={{ group.id }}">Controller</a>
                {% else %}
                    <a href="#" onclick="set_status('group', '{{ group.id }}', 'true', '{% url 'perf:set_status' %}')">Enabled</a>
                {% endif %}
                {% if plan_id %}
                    <a href="#" onclick="Delete('{% url 'perf:delete' %}', '{% url 'perf:group_home' %}?id={{ plan_id }}', 'group', {{ group.id }})">Delete</a>
                {% else %}
                    <a href="#" onclick="Delete('{% url 'perf:delete' %}', '{% url 'perf:group_home' %}', 'group', {{ group.id }})">Delete</a>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
{% endblock %}
{% block define_js %}
    <script type="text/javascript">
        let url = '{% url 'perf:group_home' %}?';
        {% if key_word %}
            url += 'keyWord={{ key_word }}&';
        {% endif %}
        {% if plan_id %}
            url += 'id={{ plan_id }}&';
        {% endif %}
        PagingManage($('#paging'), {{ total_page }}, {{ page }}, url + 'page=');
    </script>
{% endblock %}